name: ci

on:
  push:
    branches:
      # Consider the Docker build push condition if changing this
      - 'main'
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      name_and_tag: ${{ steps.variables.outputs.name_and_tag }}

    steps:
      - uses: twisted/python-info-action@v1

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Define variables
        id: variables
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          python .github/set_variables.py

      - name: Show variables
        env:
          VARIABLES: ${{ toJSON(steps.variables.outputs) }}
        shell: python
        run: |
          import os

          print(os.environ["VARIABLES"])

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download C2Prog archive
        run: |
          curl --location --output C2Prog.tar.gz "${{ fromJSON(steps.variables.outputs.c2prog_url) }}"

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ fromJSON(steps.variables.outputs.name_and_tag) }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Test
        run: |
          docker run --pull never --interactive --rm ${{ fromJSON(steps.variables.outputs.name_and_tag) }} -target | tee run.log
          grep --quiet 'Missing option -bin or -ehx!' run.log

          docker run --pull never --interactive --rm --entrypoint bash ${{ fromJSON(steps.variables.outputs.name_and_tag) }} -c "GIT_TERMINAL_PROMPT=0 git clone https://github.com/actions/checkout"

          cd example
          ls -l
          docker run --pull never --volume "$(pwd)/custom_demo.xml":/targets/custom_demo.xml --volume "$(pwd)":/data --rm ${{ fromJSON(steps.variables.outputs.name_and_tag) }} -create="z:/data/result.ehx" -bin="z:/data/test_2838x_c28_cpu01.out" -target=28388,6,4-CPU1_XBL-Demo
          ls -l
          [[ "$(stat -c %s test_2838x_c28_cpu01.ehx)" -eq "$(stat -c %s result.ehx)" ]]

      - name: Report size
        run: |
          mkdir report_size
          cd report_size
          docker save ${{ fromJSON(steps.variables.outputs.name_and_tag) }} | gzip > c2p.tar.gz
          ls -lh c2p.tar.gz
          rm c2p.tar.gz

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ fromJSON(steps.variables.outputs.publish) }}
        with:
          username: ${{ fromJSON(steps.variables.outputs.dockerhub_username) }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Push
        uses: docker/build-push-action@v2
        if: ${{ fromJSON(steps.variables.outputs.publish) }}
        with:
          context: .
          push: true
          tags: ${{ fromJSON(steps.variables.outputs.name_and_tag) }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        if: ${{ fromJSON(steps.variables.outputs.publish) }}
        with:
          username: ${{ fromJSON(steps.variables.outputs.dockerhub_username) }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ fromJSON(steps.variables.outputs.name) }}

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: This
        shell: python
        run: |
          import this
