name: ci

on:
  push:
    branches:
      # Consider the Docker build push condition if changing this
      - 'main'
  pull_request:
    branches:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - c2prog_url: http://permanent.fstab.net/c2prog/C2Prog-v1.8.10-r1.tar.gz
            name: altendky/c2prog
            tag: latest
            # Consider the triggering branches if changing this
            publish: ${{ github.event_name == 'push' && github.event.base_ref == 'main' }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download C2Prog archive
        run: |
          curl --location --output C2Prog.tar.gz "${{ matrix.c2prog_url }}"

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ matrix.name }}:${{ matrix.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Test
        run: |
          docker run --interactive --pull never --rm ${{ matrix.name }}:${{ matrix.tag }} -target | tee run.log
          grep --quiet 'Missing option -bin or -ehx!' run.log

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ matrix.publish }}
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Push
        uses: docker/build-push-action@v2
        if: ${{ matrix.publish }}
        with:
          push: true
          tags: ${{ matrix.name }}:${{ matrix.tag }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        if: ${{ matrix.publish }}
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ matrix.name }}

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - docker
    steps:
      - name: This
        shell: python
        run: |
          import this
