name: ci

on:
  push:
    branches:
      # Consider the Docker build push condition if changing this
      - 'main'
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      name_and_tag: ${{ steps.variables.outputs.name_and_tag }}

    steps:
      - uses: twisted/python-info-action@v1

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Define variables
        id: variables
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          python .github/set_variables.py

      - name: Show variables
        env:
          VARIABLES: ${{ toJSON(steps.variables.outputs) }}
        shell: python
        run: |
          import os

          print(os.environ["VARIABLES"])

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download C2Prog archive
        run: |
          curl --location --output C2Prog.tar.gz "${{ fromJSON(steps.variables.outputs.c2prog_url) }}"

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ fromJSON(steps.variables.outputs.name_and_tag) }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Test
        run: |
          ./test.sh ${{ fromJSON(steps.variables.outputs.name_and_tag) }}

      - name: Report size
        run: |
          mkdir report_size
          cd report_size
          docker save ${{ fromJSON(steps.variables.outputs.name_and_tag) }} | gzip > c2p.tar.gz
          ls -lh c2p.tar.gz
          rm c2p.tar.gz

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ fromJSON(steps.variables.outputs.publish) }}
        with:
          username: ${{ fromJSON(steps.variables.outputs.dockerhub_username) }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Push
        uses: docker/build-push-action@v2
        if: ${{ fromJSON(steps.variables.outputs.publish) }}
        with:
          context: .
          push: true
          tags: ${{ fromJSON(steps.variables.outputs.name_and_tag) }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        if: ${{ fromJSON(steps.variables.outputs.publish) }}
        with:
          username: ${{ fromJSON(steps.variables.outputs.dockerhub_username) }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ fromJSON(steps.variables.outputs.name) }}

  run:
    runs-on: ubuntu-latest
    container:
      image: ${{ fromJSON(needs.build.outputs.name_and_tag) }}
      options: --user 1000
    needs:
      - build

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check Dockerfile
        run: |
          cat Dockerfile

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - build
      - run
    steps:
      - name: This
        shell: python
        run: |
          import this
