name: ci

on:
  push:
    branches:
      # Consider the Docker build push condition if changing this
      - 'main'
  pull_request:
    branches:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download C2Prog archive
        run: |
          curl --location --output C2Prog.tar.gz http://permanent.fstab.net/c2prog/C2Prog-v1.8.10-r1.tar.gz

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: altendky/c2prog:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Test
        run: |
          docker run --interactive --pull never --rm --tty altendky/c2prog:latest -target | tee run.log
          grep 'Missing option -bin or -ehx!' run.log

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Push
        uses: docker/build-push-action@v2
        with:
          # Consider the triggering branches if changing this
          push: ${{ github.event_name == 'push' && github.event.base_ref == 'main' }}

