name: ci

on:
  push:
    branches:
      # Consider the Docker build push condition if changing this
      - 'main'
  pull_request:
    branches:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args:
            - C2PROG_ARCHIVE=http://permanent.fstab.net/c2prog/C2Prog-v1.8.10-r1.tar.gz
          # Consider the triggering branches if changing this
          push: ${{ github.event_name == 'push' && github.event.base_ref == 'main' }}
          tags: altendky/c2prog:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
